stages:
  - check
  - build
  - publish

check:
  image: denoland/deno:debian-2.3.6
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      exists:
      - "**/*.ts"
  script:
    - deno lint src
    - deno test
    - deno publish --dry-run
    - apt-get update && apt-get install -y curl gnupg
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - deno run -A scripts/build_npm.ts @iacobus/hd 0.0.0
    - cd npm
    - npm publish --dry-run --tag check

build:
  image: denoland/deno:debian-2.3.6
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      exists:
      - "**/*.ts"
  script:
    - export TAG_VERSION=${CI_COMMIT_TAG/v/}
    - apt-get update && apt-get install -y curl gnupg
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - deno run -A ./scripts/build_npm.ts @iacobus/hd $TAG_VERSION
  artifacts:
    paths:
      - npm/

publish:
  image: node:20
  stage: publish
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
      exists:
      - "**/*.js"
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - cd npm
    - npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
    - npm publish --provenance --access public